### PR TITLE
Tying to fix problem with values

### PR DESCRIPTION
**Pull request by raul-bns**
Hi, I'm using the plugin, and I'm very happy but after install a new version of treesitter i was having problems with the way injections are handeled. I've started to try to fix it and I've arrived until here. I'm able to not make vim stop. But this isn't working really properly. I've never done anny thing with treesitter, I've regarded a little bit in treesitter code to check how to fix it but i dont arrive well. Any help will be appreciated. I really like this pluging.

### CODE REVIEW

**Comment by gbprod** [comment]
OH! It seems that the last tree-sitter-php update broke the queries ! (probably [this commit](https://github.com/tree-sitter/tree-sitter-php/commit/279862597e2937c99c33c27d963880b967cd5d75))
Thanks for your PR, I think with queries like that it will works : 

```query
(
    [
        (string_content) @injection.content
        (nowdoc value: (nowdoc_body) @injection.content) 
        (heredoc value: (heredoc_body) @injection.content) 
    ] 
    (#set! injection.language "sql")
    (#set! injection.include-children)
    (#lua-match? @injection.content "^%s*[Ss][Ee][Ll][Ee][Cc][Tt]%s+.+[Ff][Rr][Oo][Mm]")
)
```

But I have an error when testing with heredoc, maybe the parser is broken...

**Comment by gbprod** [comment]
Here is the heredoc issue : https://github.com/tree-sitter/tree-sitter-php/issues/238

**Comment by raul-bns** [comment]
I've changed the queries into the version you gave me. Also the heredoc still broked.

**Comment by gbprod** [comment]
Hey!

Queries are fixed with my latest commit : https://github.com/gbprod/php-enhanced-treesitter.nvim/commit/93acad6b51750c15f022a27ab14b958b7f8173b6
The heredoc issue still here but not link to this plugin.

Thanks!

**Pull request closed without merging**
