### PR TITLE
[fix] separates each regex to make it works

### PR DESCRIPTION
**Pull request by raul-bns**
I've tested with the test.php file and it works now for all type of queries.

### CODE REVIEW

**Comment by gbprod** [comment]
Hey!
Which version of neovim are you using ?

**Comment by gbprod** [comment]
It seems that "any-lua-match" exist since neovim 0.10.
I'll put a tag on a commit for compatibility.

**Comment by gbprod** [comment]
That's fixed, thanks !

**Comment by raul-bns** [comment]
I'm using nvim version 10.

**Pull request merged**
