### PR TITLE
Add html string injections, make queries more advanced

### PR DESCRIPTION
**Pull request by kedodrill**
The first two injections are for HTML. I updated the queries to try and eliminate false positives, but there are still some that exist. `WITH` is still pretty barebones, and `EXPLAIN` is the same...do you know how to define variables in scheme? I tried `(define (select "..."))` but that didn't work. If we could define vars, that would make this way easier...and explain could be made better.

I also removed `REPLACE` since it's a function and not a keyword. I can put it back if you want, but I don't think there's a way for it to be highlighted correctly with how it was set up.

here are some examples

### CODE REVIEW

**Comment by gbprod** [comment]
Interesting!
Does it works if queries contains new lines ?

**Comment by gbprod** [comment]
As far as I know, this is not possible to create variables in scheme :sweat_smile:

**Comment by kedodrill** [comment]
> Interesting! Does it works if queries contains new lines ?

It does, I had tested that but guess I erased that in the screenshot.

here is another example with just newline and the second one has a tab character

> As far as I know, this is not possible to create variables in scheme 😅

Well, that's too bad. Would make this a lot easier instead of having to keep up with all the different types of strings. Oh well!

**Comment by gbprod** [comment]
Thanks !!

**Pull request merged**
